-- SPDX-License-Identifier: ODbL-1.0
-- Genshin Impact content and materials are a copyright of miHoYo Co., Ltd. All rights reserved.

PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: InventoryItems
CREATE TABLE InventoryItems (UserId INTEGER, ChatId INTEGER, ItemId STRING, Count INTEGER DEFAULT (0), PRIMARY KEY (UserId, ChatId, ItemId));

-- Table: Items
CREATE TABLE Items (Id STRING PRIMARY KEY, Name STRING, Type STRING, Stars INTEGER, Description STRING, Image STRING);
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('ganyu', 'Ganyu', 'Character', 5, 'All hail!', 'AgACAgIAAxkBAAICMmAW_GG6vB2ABO_2eJmnQ2JiGNYAA-azMRtRzbhI-eyPSH19g2DrT_OXLgADAQADAgADeQADdFMGAAEeBA');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('amber', 'Amber', 'Character', 4, 'Go, go, Baron Bunny!', 'AgACAgIAAxkBAAICFGAW-6f6HvZl_KqAtBLpNtpgVye8AAL1sjEbMRq5SEoYtjJaAumJVKh0ly4AAwEAAwIAA3kAA795BgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('barbara', 'Barbara', 'Character', 4, 'I wonder when I''ll be as tall as my big sister...', 'AgACAgIAAxkBAAICFmAW-7QFyCwSIzKLVsY3P2LocRbGAALYszEbUc24SJNZ12G1FohKZ1oTmC4AAwEAAwIAA3kAA8piBgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('beidou', 'Beidou', 'Character', 4, 'Eyes on me!', 'AgACAgIAAxkBAAICGGAW-84dzDr2vr7_h2ze6Xuh5en5AALZszEbUc24SDgyktC5bpBfshNwly4AAwEAAwIAA3kAAzh3BgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('bennett', 'Bennett', 'Character', 4, 'Teamwork is dreamwork!', 'AgACAgIAAxkBAAICGmAW-9UYK8xHIvo9L4omexwc5yJAAALaszEbUc24SLqZC6bW5B_KnnEXmy4AAwEAAwIAA3kAA3coAQABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('chongyun', 'Chongyun', 'Character', 4, 'From whence you came!', 'AgACAgIAAxkBAAICHGAW-914ui8TLEhQdSLP6B1r4FXlAALbszEbUc24SOx7F6YvygtIy0Lwly4AAwEAAwIAA3kAAyNFBgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('diluc', 'Diluc', 'Character', 5, 'Time for... RETRIBUTION!', 'AgACAgIAAxkBAAICNGAW_GxXUV7MKadJPXnNh8JmdrxiAALnszEbUc24SDaNBbUKeeaVcRjnly4AAwEAAwIAA3kAA-hgBgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('diona', 'Diona', 'Character', 4, 'Think you can bully me?', 'AgACAgIAAxkBAAICHmAW--SMX4VJlcQVO5ARDjqg2xg2AALcszEbUc24SDd-ai2GkdIL9AZtly4AAwEAAwIAA3kAA9duBgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('fischl', 'Fischl', 'Character', 4, 'Midnight Phantasmagoria!', 'AgACAgIAAxkBAAICIGAW-_N0vL96brHLxJLkBxheHN5zAALdszEbUc24SLBheNumqQ6qyQ48my4AAwEAAwIAA3kAAwrtAQABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('jean', 'Jean', 'Character', 5, 'Barbatos, guide us!', 'AgACAgIAAxkBAAICNmAW_HSoM8kMkJLBLY3JL-HEhBuWAALoszEbUc24SG_516wl5mEQwGiJni4AAwEAAwIAA3kAA1I1AQABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('kaeya', 'Kaeya', 'Character', 4, 'Don''t get frostbite!', 'AgACAgIAAxkBAAICImAW_AFJpB1vLEYcT8W5KOQY-FwUAALeszEbUc24SOjjZDDRtAGZGEtdmi4AAwEAAwIAA3kAAxMsBAABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('coolsteel', 'Cool Steel', 'Weapon', 3, 'A reliable steel-forged weapon.', 'AgACAgIAAxkBAAIBzmAW-S8bBgO8lNN3DQKaw33bopDyAAKsszEbUc24SO63A3FPpz6GRpPlly4AAwEAAwIAA20AA3xnBgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('blacktassel', 'Black Tassel', 'Weapon', 3, 'An exceptionally powerful polearm.', 'AgACAgIAAxkBAAIBzGAW-N1B0f2zZ8yMXBAp-6icGlXtAAL0sjEbMRq5SDT5snbxi7YNa8YOmC4AAwEAAwIAA20AA9BlBgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('skyridergreat', 'Skyrider Greatsword', 'Weapon', 3, 'A reliable steel sword.', 'AgACAgIAAxkBAAIB1mAW-bc8yyb5kfaWyNzb7PNybXTqAAK0szEbUc24SJqJM46cT69XMXA0my4AAwEAAwIAA20AA3QNAgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('ferrousshadow', 'Ferrous Shadow', 'Weapon', 3, 'A replica of the famed sword of Arundolyn, the Lion of Light.', 'AgACAgIAAxkBAAIB0WAW-VpCFun_h49aENumINvVwvPIAAKvszEbUc24SCWLnU2JdEns_MvKmS4AAwEAAwIAA20AA5HxAwABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('debate', 'Debate Club', 'Weapon', 3, 'A handy club made of fine steel.', 'AgACAgIAAxkBAAIBz2AW-TvoTxgr9CfoXyRW52B0WWioAAKtszEbUc24SOtFX-3jQAJh90DRmi4AAwEAAwIAA20AA58rAQABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('thrillingtales', 'Thrilling Tales of Dragon Slayers', 'Weapon', 3, 'A fictional story of a band of five heroes who go off on a dragon hunt.', 'AgACAgIAAxkBAAIB2WAW-dfShF7IpanQAsKH-kk4BRWiAAK3szEbUc24SNHbvUvmtsvcXd8UmC4AAwEAAwIAA20AA7JlBgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('magicguide', 'Magic Guide', 'Weapon', 3, 'The most authoritative guide to magic in existence.', 'AgACAgIAAxkBAAIB02AW-XRAEjHvnqPCmOPqlArnESsbAAKxszEbUc24SMqE9cH2GgXzCvLAly4AAwEAAwIAA20AA7o8BgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('emerald', 'Emerald Orb', 'Weapon', 3, 'A catalyst carved out of the hard jade from Jueyunjian north of Liyue.', 'AgACAgIAAxkBAAIB0GAW-Ui_Yx21jP6DXmO5AwnSWZlGAAKuszEbUc24SNv8Y_pb11bKefpply4AAwEAAwIAA20AAyZ3BgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('slingshot', 'Slingshot', 'Weapon', 3, 'A bow, despite the name.', 'AgACAgIAAxkBAAIB2GAW-cw9vT58a93D7Z6kQGb4D4eqAAK2szEbUc24SLbn-wlrHuYZnLVFmC4AAwEAAwIAA20AA21gBgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('sharpshooter', 'Sharpshooter''s Oath', 'Weapon', 3, 'This superior bow once belonged to a master archer.', 'AgACAgIAAxkBAAIB1WAW-atiXSL6_bz_IiC5_jnpxaAWAAKzszEbUc24SPCboHbjWj5Kodovmy4AAwEAAwIAA20AA1LmAQABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('ravenbow', 'Raven Bow', 'Weapon', 3, 'Bow''s limb is decorated with raven feathers.', 'AgACAgIAAxkBAAIB1GAW-YIccA9mSWh5yBYJ_kVpdh3pAAKyszEbUc24SF4faeoAAfWomIhB8JcuAAMBAAMCAANtAANFVAYAAR4E');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('albedo', 'Albedo', 'Character', 5, 'Moment of birth!', 'AgACAgIAAxkBAAICOGAW_H1xnRBcEncygDFEIc0UsJI3AALpszEbUc24SEZkDOO7qP2hd1Zgmi4AAwEAAwIAA3kAA3QkBAABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('zhongli', 'Zhongli', 'Character', 5, 'I WILL HAVE ORDER!', 'AgACAgIAAxkBAAICOmAW_IWZw3KS5QABws4jcRtiMWzNSQAC6rMxG1HNuEiVBCbTTd7m-YTuip4uAAMBAAMCAAN5AANWMAEAAR4E');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('xiao', 'Xiao', 'Character', 5, 'Evil conquering!', 'AgACAgIAAxkBAAICPGAW_I3VH-8vW2HV6ccwfqjfRWzUAALrszEbUc24SEPq5MIg4G4FTPDdly4AAwEAAwIAA3kAA2g8BgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('xingqiu', 'Xingqiu', 'Character', 4, 'Witness the power of Guhua!', 'AgACAgIAAxkBAAICJGAW_BU9CaFYRNGMK0pC8gvhDeLYAALfszEbUc24SKsmv6EDrTG7minNly4AAwEAAwIAA3kAAxo1BgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('xiangling', 'Xiangling', 'Character', 4, 'Out of the frying pan into the fire!', 'AgACAgIAAxkBAAICJmAW_B1YNvRz7LJ0_AywldIylX7aAALgszEbUc24SAIUkNysIZXIiLUHni4AAwEAAwIAA3kAA0UxAQABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('venti', 'Venti', 'Character', 5, 'Time for take-off!', 'AgACAgIAAxkBAAICPmAW_JQsxFU2sRaxasxieAykZRPlAALsszEbUc24SKFA2y0qFD0iGEsQmC4AAwEAAwIAA3kAA85jBgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('tartaglia', 'Tartaglia', 'Character', 5, 'You can run but you can''t hide!', 'AgACAgIAAxkBAAICQGAW_JubfgukG3EWgP-Bwl-jKQZ3AALtszEbUc24SAEhTTem-0aO0ukymy4AAwEAAwIAA3kAA3EPAgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('sucrose', 'Sucrose', 'Character', 4, 'I haven''t been out in a while...', 'AgACAgIAAxkBAAICKGAW_CXQktCZjzvOOdUXuQSwQrs8AALhszEbUc24SKI7MbQjfWVFGqJMli4AAwEAAwIAA3kAAwr-BgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('razor', 'Razor', 'Character', 4, 'I''m hungry. Let''s hunt!', 'AgACAgIAAxkBAAICKmAW_CygT4RcVNqe_1ESvkuVcKOHAALiszEbUc24SHJ5wWYaQig8Jxvnly4AAwEAAwIAA3kAA3ppBgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('qiqi', 'Qiqi', 'Character', 5, 'Orders given. Orders received.', 'AgACAgIAAxkBAAICQmAW_KULs_HT3MwOHF6hL9xHkjQ4AALuszEbUc24SEw4HYdk4P1GtcXSmi4AAwEAAwIAA3kAA5E7AQABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('noelle', 'Noelle', 'Character', 4, 'As a dutiful maid would!', 'AgACAgIAAxkBAAICLGAW_DP632BF9nIesMvq8DZUjJOqAALjszEbUc24SA1Tl_MO0bBTV2UWmC4AAwEAAwIAA3kAAwdpBgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('ningguang', 'Ningguang', 'Character', 4, 'We should look for a new investment. Mora doesn''t grow on trees.', 'AgACAgIAAxkBAAICLmAW_EcPf1wZHmi_MMIoFx24NuFVAALkszEbUc24SMYKbkxyg4gplZpxly4AAwEAAwIAA3kAA1ZwBgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('mona', 'Mona', 'Character', 5, 'Shadows of fate!', 'AgACAgIAAxkBAAICRGAW_KwWLigFZ6cnxitLEsFTpzt3AALvszEbUc24SLuVemKqg5IPjBjnly4AAwEAAwIAA3kAAxZqBgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('lisa', 'Lisa', 'Character', 4, 'Try not to enjoy this too much...', 'AgACAgIAAxkBAAICMGAW_E_Quib8O19ErRL1UC8uELUzAALlszEbUc24SITebbNzsqCY6kHwly4AAwEAAwIAA3kAA1BQBgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('klee', 'Klee', 'Character', 5, 'Boink-boink-BOOM!', 'AgACAgIAAxkBAAICRmAW_LOxopgJRgEm3Af5n-7bjnDEAALwszEbUc24SDVmIfmsLOX04fDdly4AAwEAAwIAA3kAA8wyBgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('keqing', 'Keqing', 'Character', 5, 'With sword comes shadow!', 'AgACAgIAAxkBAAICSGAW_LrSbLl71AABgZ0fVCyEl7YnKgAC8bMxG1HNuEjPzjEvTIz_P1ZIXZouAAMBAAMCAAN5AAOlMAQAAR4E');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('bloodtainted', 'Bloodtainted Greatsword', 'Weapon', 3, 'A steel sword that is said to have been coated with dragon blood.', 'AgACAgIAAxkBAAIBzWAW-R8xLHi_ZBWATfcknxSACjxQAAKrszEbUc24SGeqMM9i0mLESecymy4AAwEAAwIAA20AA5IQAgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('harbinger', 'Harbinger of Dawn', 'Weapon', 3, 'A sword that once shone like the sun.', 'AgACAgIAAxkBAAIB0mAW-WbOJXXEwdVc9URE6V-75P6jAAKwszEbUc24SC_3a-7K0oaIcJY9my4AAwEAAwIAA20AAxrkAQABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('favsword', 'Favonius Sword', 'Weapon', 4, 'A standard-issue longsword of the Knights of Favonius.', 'AgACAgIAAxkBAAIB3mAW-ikTPXc1waZdfn_ntft8czp4AAK8szEbUc24SJ8W6Q-9KzDug80Nni4AAwEAAwIAA20AA3QxAQABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('flute', 'The Flute', 'Weapon', 4, 'Beneath its rusty exterior is a lavishly decorated thin blade. It swings as swiftly as the wind.', 'AgACAgIAAxkBAAIB32AW-jWdyJYm-8jK5FoU_52oqC0NAAK-szEbUc24SNdGah9fw8Fi7rSUly4AAwEAAwIAA20AAzleBgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('favgreatsword', 'Favonius Greatsword', 'Weapon', 4, 'A heavy ceremonial sword of the Knights of Favonius.', 'AgACAgIAAxkBAAIB4GAW-n4eA6ZqGqp8mgeETucleTAbAAK_szEbUc24SBBKLwTnD3JqzxJwly4AAwEAAwIAA20AA8V0BgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('sacgreatsword', 'Sacrificial Greatsword', 'Weapon', 4, 'A ceremonial greatsword that has become petrified over time.', 'AgACAgIAAxkBAAIB4mAW-ojoA3DiI8gFDFC-seYNoiyyAALAszEbUc24SF6LMgeB-MvajbNFmC4AAwEAAwIAA20AA3VdBgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('rainslasher', 'Rainslasher', 'Weapon', 4, 'A fluorescent greatsword with no sharp edge that crushes enemies with brute force and raw power.', 'AgACAgIAAxkBAAIB5GAW-o9wR0w8MNkVWmgUjyq6Ty7rAALBszEbUc24SH1HAvwlJ1-Nf11Mni4AAwEAAwIAA20AAzUvAQABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('favlance', 'Favonius Lance', 'Weapon', 4, 'A polearm made in the style of the Knights of Favonius.', 'AgACAgIAAxkBAAIB5mAW-pftKqbcQoDVmzUVgviT_SiFAALCszEbUc24SAVKag9CDthPx7KUly4AAwEAAwIAA20AA6phBgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('favcodex', 'Favonius Codex', 'Weapon', 4, 'A secret tome that belonged to the scholars of the Knights of Favonius.', 'AgACAgIAAxkBAAIB3WAW-g6B5z1pinYyaFz12OJZ3D6IAAK7szEbUc24SHhs3TWqPnP2V88Pmy4AAwEAAwIAA20AAyxIAQABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('widsith', 'The Widsith', 'Weapon', 4, 'A heavy notebook filled with musical scores.', 'AgACAgIAAxkBAAIB6GAW-p64ka9lyOtqNl2zkq8I_PMnAALDszEbUc24SGKnxnroI7DATEwQmC4AAwEAAwIAA20AA51cBgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('sacframents', 'Sacrificial Fragments', 'Weapon', 4, 'A weathered script, the text of which is no longer legible.', 'AgACAgIAAxkBAAIB6mAW-qXfFK7dz6wHQT8I58qgY6HpAALEszEbUc24SCsRNF9No259lh4imy4AAwEAAwIAA20AAxMVAgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('stringless', 'The Stringless', 'Weapon', 4, 'A bow that once served as an extraordinary instrument.', 'AgACAgIAAxkBAAIB7GAW-qwlLk3YTnLd-nbp-BI6c73bAALFszEbUc24SCMfyKgP6ehDtO2Kni4AAwEAAwIAA20AA5Y2AQABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('sacbow', 'Sacrificial Bow', 'Weapon', 4, 'A ceremonial hunting bow that has become petrified over time.', 'AgACAgIAAxkBAAIB7mAW-rPzkH2Nr5IzkuMgtZMRDvsEAALGszEbUc24SP63sxMgm-V7SKzrly4AAwEAAwIAA20AAwZrBgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('rust', 'Rust', 'Weapon', 4, 'A completely rusted iron greatbow.', 'AgACAgIAAxkBAAIB8GAW-rtGJBA8gNRK_27kniNYYK-UAALHszEbUc24SIggxYzYYRrU4DlHmC4AAwEAAwIAA20AA5piBgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('sacsword', 'Sacrificial Sword', 'Weapon', 4, 'A ceremonial sword that has become petrified over time.', 'AgACAgIAAxkBAAIDg2ApPREQ91uugzrKYZl2X_uAgbxNAALxsDEbQgVJSUzQ_uvLPC_vEqcjmy4AAwEAAwIAA20AA2KuAgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('bell', 'The Bell', 'Weapon', 4, 'A clock is embedded within the sword, though its internal mechanisms have long been damaged.', 'AgACAgIAAxkBAAIDgWApPK6pxulzmV9Mo7uM42KNCvoZAALvsDEbQgVJSU_yZSVQxcn3F9VWmS4AAwEAAwIAA20AA7LvBAABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('dragonbane', 'Dragon''s Bane', 'Weapon', 4, 'A polearm decorated with an entwining golden dragon.', 'AgACAgIAAxkBAAIB22AW-fdeCZ3QhrEbj-o9sVOlGw0tAAK5szEbUc24SP1nHD09wXs9wPVBli4AAwEAAwIAA20AA7T2BgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('eyeperception', 'Eye of Perception', 'Weapon', 4, 'A dim black glaze pearl that is said to have the power to reach the purity of one''s heart.', 'AgACAgIAAxkBAAIB3GAW-gMp7f2xwU5qd7tE4Om2n5MSAAK6szEbUc24SNtNroN-ztxm8joomy4AAwEAAwIAA20AA9wRAgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('favwarbow', 'Favonius Warbow', 'Weapon', 4, 'A standard-issue recurve bow of the Knights of Favonius.', 'AgACAgIAAxkBAAIB9GAW-spQQMPUrwgDs2kL1K6MaXQvAALIszEbUc24SPiQRgwSp48cOaFpli4AAwEAAwIAA20AA_v3BgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('memoryofdust', 'Memory of Dust', 'Weapon', 5, 'A stone dumbbell containing distant memories. Its endless transformations reveal the power within.', 'AgACAgIAAxkBAAIB-GAW-u7QHzbBrtuZgMkn2bwTodmhAALKszEbUc24SHmLniw_5CV1cavrly4AAwEAAwIAA20AA3NlBgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('unforged', 'The Unforged', 'Weapon', 5, 'Capable of driving away evil spirits and wicked people alike, this edgeless claymore seems to possess divine might.', 'AgACAgIAAxkBAAIB-mAW-vWFlZjsMvlQhJDdljILkMtlAALLszEbUc24SGdfLTSn8XANr05VmS4AAwEAAwIAA20AA3wyBAABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('vortexvanqui', 'Vortex Vanquisher', 'Weapon', 5, 'This sharp polearm can seemingly pierce through anything. When swung, one can almost see the rift it tears in the air.', 'AgACAgIAAxkBAAIB_GAW-vt--6BKXk0bTySw5masDA4qAALMszEbUc24SGizHyGDO3X4qwvkly4AAwEAAwIAA20AAx5sBgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('summitshaper', 'Summit Shaper', 'Weapon', 5, 'A symbol of a legendary pact, this sharp blade once cut off the peak of a mountain.', 'AgACAgIAAxkBAAIB_mAW-wFjtgs4JBJLJUmLj_Kil8n5AALNszEbUc24SJzaLLhJM3GUBWaJni4AAwEAAwIAA20AA2k2AQABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('aquila', 'Aquila Favonia', 'Weapon', 5, 'The sword of the Knights of Favonius. Millennia later, it still calls on the winds of swift justice to vanquish all evil�just like the last heroine who wielded it.', 'AgACAgIAAxkBAAICAAFgFvsIWJcechZRcL8aR8W_9pn89AACzrMxG1HNuEhEduGu_HNOJvX2GJsuAAMBAAMCAANtAAOJKwEAAR4E');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('skyblade', 'Skyward Blade', 'Weapon', 5, 'The sword of a knight that symbolizes the restored honor of Dvalin. The blessings of the Anemo Archon rest on the fuller of the blade, imbuing the sword with the powers of the sky and the wind.', 'AgACAgIAAxkBAAICAmAW-w8RSKj5P02xNA3PhUj0SIc5AALPszEbUc24SDWZy8qnqIDYu3Joly4AAwEAAwIAA20AA6x4BgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('wolfstone', 'Wolf''s Gravestone', 'Weapon', 5, 'A longsword used by the Wolf Knight. Originally just a heavy sheet of iron given to the knight by a blacksmith from the city, it became endowed with legendary power owing to his friendship with the wolves.', 'AgACAgIAAxkBAAICBGAW-xYWS4WhTTThMsoXBuCMJZw8AALQszEbUc24SCCKPIFa8qFXz79ImC4AAwEAAwIAA20AA-9bBgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('skyspine', 'Skyward Spine', 'Weapon', 5, 'A polearm that symbolizes Dvalin''s fire resolve. The upright shaft of this weapon points towards the heavens, clad in the might of sky and wind.', 'AgACAgIAAxkBAAICBmAW-x7pMAKxDeAFUfMXG8qnOrSjAALRszEbUc24SN5hCQbz5Yx1xA48my4AAwEAAwIAA20AAyDsAQABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('jadespear', 'Primordial Jade Winged-Spear', 'Weapon', 5, 'A jade polearm made by the archons, capable of slaying ancient beasts.', 'AgACAgIAAxkBAAICCGAW-yWbAZpr0fjHySYpu4l0k12XAALSszEbUc24SKNgfxP2S9ABleuKni4AAwEAAwIAA20AA6gyAQABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('skyatlas', 'Skyward Atlas', 'Weapon', 5, 'A cloud atlas symbolizing Dvalin and its former master, the Anemo Archon. It details the winds and clouds of the northern regions and contains the powers of the sky and wind.', 'AgACAgIAAxkBAAICCmAW-ywhoMMbecbqlFfF8E6F4dtZAALTszEbUc24SNANdnzEv3w5OGxAli4AAwEAAwIAA20AA2H8BgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('lostprayer', 'Lost Prayer to the Secret Winds', 'Weapon', 5, 'An educational tome written by anonymous early inhabitants who worshiped the wind. It has been blessed by the wind for its faithfulness and influence over the millennia.', 'AgACAgIAAxkBAAICDGAW-zPKeZy1nAbstpgkiIp9PpFIAALUszEbUc24SNaPnMoIkwx0N0sQmC4AAwEAAwIAA20AA-VgBgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('skyharp', 'Skyward Harp', 'Weapon', 5, 'A greatbow that symbolizes Dvalin''s affiliation with the Anemo Archon. The sound of the bow firing is music to the Anemo Archon''s ears. It contains the power of the sky and wind within.', 'AgACAgIAAxkBAAICDmAW-zhpx4hecz-Eo-SSpYuPexV7AALVszEbUc24SKOafWihtejYV1YRmy4AAwEAAwIAA20AA0csAQABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('skypride', 'Skyward Pride', 'Weapon', 5, 'A claymore that symbolizes the pride of Dvalin soaring through the skies. When swung, it emits a deep hum as the full force of Dvalin''s command of the sky and the wind is unleashed.', 'AgACAgIAAxkBAAICEGAW-z5FcycN9tQsNu7pOrshcHTuAALWszEbUc24SKhEum6zFiQBFptxly4AAwEAAwIAA20AAyttBgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('amos', 'Amos'' Bow', 'Weapon', 5, 'An extremely ancient bow that has retained its power despite its original master being long gone. It draws power from everyone and everything in the world, and the further away you are from that which your heart desires the more.', 'AgACAgIAAxkBAAICEmAW-0Wo5v45DA9CIYCF4sbb7gluAALXszEbUc24SO_5iAMB1dqc6vhply4AAwEAAwIAA20AA-dwBgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('lionroar', 'Lion''s Roar', 'Weapon', 4, 'A sharp blade that roars like a lion as it cuts through the air.', 'AgACAgIAAxkBAAIB9mAW-th6pO8zl0sPJ5xgs3l7M41sAALJszEbUc24SK5XGkMNt8bzg91hmi4AAwEAAwIAA20AA7EnBAABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('skyridersword', 'Skyrider Sword', 'Weapon', 3, 'A reliable steel sword.', 'AgACAgIAAxkBAAIB12AW-cFDUQzru5r-GVo2GxBY70LSAAK1szEbUc24SCBcLR7kP0MSuwhtly4AAwEAAwIAA20AA3B1BgABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('jadecutter', 'Primordial Jade Cutter', 'Weapon', 5, 'A ceremonial sword masterfully carved from pure jade. There almost seems to be an audible sigh in the wind as it is swung.', 'AgACAgIAAxkBAAEJGlJgMV5E-lDde9dYHX8uStQAAZ8jkMIAAjKyMRsH3IlJGDzRuTUp5XfewSmbLgADAQADAgADbQADQ1cDAAEeBA');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('hutao', 'Hu Tao', 'Character', 5, 'Pyre-pyre, pants on fire!', 'AgACAgIAAxkBAAIJGWBYJlClYf9Cl5nWmD5ZKp7N_qDdAAJmtzEb-lzISvFASqcew8KaBLSZoS4AAwEAAwIAA3kAA9cWAAIeBA');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('homastaff', 'Staff of Homa', 'Weapon', 5, 'A "firewood staff" that was once used in ancient and long-lost rituals.', 'AgACAgIAAxkBAAIJGmBYJlrr0r0Utio04jnqAAEQOSmfvQACZ7cxG_pcyErW8ljwgqYseV4flaEuAAMBAAMCAANtAAM8FwACHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('lithicblade', 'Lithic Blade', 'Weapon', 4, 'A greatsword carved and chiseled from the very bedrock of Liyue.', 'AgACAgIAAxkBAAIJHGBYJmZ67xTZDu-a8MtGyAikdGSOAAJptzEb-lzISnm1Xvin_ivsMGRQmC4AAwEAAwIAA20AA4d2BwABHgQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('lithicspear', 'Lithic Spear', 'Weapon', 4, 'A spear forged from the rocks of the Guyun Stone Forest. Its hardness knows no equal.', 'AgACAgIAAxkBAAIJHWBYJmrO3ftmg_Bd94Gg7seJi9VFAAJqtzEb-lzISvlk8fL1w8l9u_4Eny4AAwEAAwIAA20AAzEWAAIeBA');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('endelegy', 'Elegy for the End', 'Weapon', 5, 'A bow as lovely as any bard''s lyre, its arrows pierce the heart like a lamenting sigh.', 'AgACAgIAAxkBAAIJG2BYJl_0myxtNZQMAwR4gmdbH7MJAAJotzEb-lzISgIUivYpcaIirwwIny4AAwEAAwIAA20AA1QXAAIeBA');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('rosaria', 'Rosaria', 'Character', 4, 'Don''t overdo it. Let me take care of the dirty work.', 'AgACAgIAAxkBAAIPMmB8cZq0wCbDqvOTCUH5MOEEOuSaAAKVsjEbLR_pS3UEtZr2a7MeRpAHoi4AAwEAAwIAA3kAA_c-AQABHwQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('yanfei', 'Yanfei', 'Character', 4, 'Wrath of the flame!', 'AgACAgIAAxkBAAIYm2Ck7aCoY_6HF0DkPcFyC8AQzrslAAIvszEbFNkgSVIuf_y-ZZQh2_ESpC4AAwEAAwIAA3kAA6FEAQABHwQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('eula', 'Eula', 'Character', 5, 'Vengeance will be mine!', 'AgACAgIAAxkBAAIYmmCk7Z1Sp8zi_CrH3ht0WBxa_cHeAAIuszEbFNkgSXJgjJGMAAH71JN2gKMuAAMBAAMCAAN5AANg_AACHwQ');
INSERT INTO Items (Id, Name, Type, Stars, Description, Image) VALUES ('brokenpines', 'Song of Broken Pines', 'Weapon', 5, 'A greatsword as light as the sigh of grass in the breeze, yet as merciless to the corrupt as a typhoon.', 'AgACAgIAAxkBAAIYmWCk7Zmu6QQdgIlFBOGYdcuueHG8AAItszEbFNkgSaf5irdOyAxhzDVDni4AAwEAAwIAA20AA4oQBAABHwQ');

-- Table: UsersInChats
CREATE TABLE UsersInChats (UserId STRING, ChatId STRING, HasRolled BOOLEAN DEFAULT (0), FourPity INTEGER DEFAULT (0), FivePity INTEGER DEFAULT (0), PRIMARY KEY (UserId, ChatId));

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
